apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: database-allow-backend
  namespace: production
spec:
  podSelector:
    matchLabels:
      app: database   # applies to database pods only
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: backend   # only backend pods
      ports:
        - protocol: TCP
          port: 5432        # PostgreSQL
  egress: [] # deny all egress
