apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: production
data:
  NODE_ENV: "production"
  PORT: "5000"
  DB_HOST: "database-statefulset-0.database-service.production.svc.cluster.local"
#  DB_HOST: "database-service"
  DB_PORT: "5432"
  DB_NAME: "student_management"
  CORS_ORIGIN: "*"
  POSTGRES_DB: "student_management"
  # Database connection optimization
  DB_MAX_CONNECTIONS: "10"
  DB_IDLE_TIMEOUT: "30000"
  DB_CONNECTION_TIMEOUT: "5000"
  DB_RETRY_DELAY: "1000"
  DB_MAX_RETRIES: "3"
