apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: production
data:
  NODE_ENV: "production"
  PORT: "5000"
  DB_HOST: "database-service"
  DB_PORT: "5432"
  DB_NAME: "student_management"
  CORS_ORIGIN: "*"
  POSTGRES_DB: "student_management"