apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: backend
  name: backend-deployment
  namespace: production
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  strategy: {}
  template:
    metadata:
      labels:
        app: backend
    spec:
      initContainers:
      - name: wait-for-database
        image: busybox:1.36
        command: ['sh', '-c', 'until nc -zv database-service 5432; do echo "Waiting for database..."; sleep 2; done']
      containers:
      - image: backend
        name: backend
        imagePullPolicy: IfNotPresent
        envFrom:
          - configMapRef:
              name: backend-config
          - secretRef:
              name: db-secret
        ports:
        - containerPort: 5000
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 2
          failureThreshold: 6
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 20
          periodSeconds: 20
          timeoutSeconds: 3
        resources:
          requests:
            cpu: "50m"
            memory: "64Mi"
          limits:
            cpu: "250m"
            memory: "256Mi"
status: {}
