apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: backend
  name: backend-deployment
  namespace: production
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  strategy: {}
  template:
    metadata:
      labels:
        app: backend
    spec:
      initContainers:
      - name: wait-for-database
        image: busybox:1.36
        command: ['sh', '-c', 'until nc -zv database-service 5432; do echo "Waiting for database..."; sleep 2; done']
      containers:
      - image: backend
        name: backend
        imagePullPolicy: IfNotPresent
        envFrom:
          - configMapRef:
              name: backend-config
          - secretRef:
              name: db-secret
        ports:
        - containerPort: 5000
        startupProbe: # While this probe is running, liveness and readiness are disabled
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 30
        readinessProbe: # Mark as pod ready for Service connections. Readiness never restarts your container.
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 15
          timeoutSeconds: 5
          failureThreshold: 3
          successThreshold: 1
        livenessProbe: # It restarts the container
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 20
          periodSeconds: 10
          timeoutSeconds: 3
        resources:
          requests:
            cpu: "50m"
            memory: "64Mi"
          limits:
            cpu: "250m"
            memory: "256Mi"
status: {}
