apiVersion: v1
kind: ConfigMap
metadata:
  name: database-config
  namespace: production
data:
  POSTGRES_DB: "student_management"
  BACKUP_HOST: "database-statefulset-1.database-service.production.svc.cluster.local"
