apiVersion: v1
kind: Service
metadata:
  name: database-service
  labels:
    app: database-service
  namespace: production
spec:
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
  clusterIP: None
  selector:
    app: database
