apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: frontend
    # env: production
  name: frontend-deployment
  namespace: production
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  strategy: {}
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - image: registry.digitalocean.com/student-app/frontend:latest
        name: frontend
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 2
          failureThreshold: 6
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 20
          periodSeconds: 20
          timeoutSeconds: 3
        resources:
          requests:
            cpu: "20m"
            memory: "16Mi"
          limits:
            cpu: "100m"
            memory: "64Mi"
status: {}
