apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend-sa
  namespace: production
  labels:
    app: backend
    component: serviceaccount
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend-sa
  namespace: production
  labels:
    app: frontend
    component: serviceaccount
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: database-sa
  namespace: production
  labels:
    app: database
    component: serviceaccount
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: monitoring-sa
  namespace: production
  labels:
    app: monitoring
    component: serviceaccount

