apiVersion: v1
kind: Pod
metadata:
  name: pvc-debug
spec:
  containers:
    - name: debug
      image: ubuntu
      command: ["sleep", "3600"]
      resources:
        requests:
          cpu: "10m"
          memory: "100Mi"
        limits:
          cpu: "100m"
          memory: "128Mi"
      volumeMounts:
        - name: db-backup-pvc
          mountPath: /backup
  volumes:
    - name: db-backup-pvc
      persistentVolumeClaim:
        claimName: db-backup-pvc
